<a href="https://colab.research.google.com/github/Aazeeb/SJCITIntershipProject/blob/main/13_Aug_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY- Numerical Python

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
#Array is an ordered collection of elements of basic data type of a given length

In [ ]:
arr1= np.array([1,3,5,4,6])

In [ ]:
arr1

array([1, 3, 5, 4, 6])

In [ ]:
print(arr1)

[1 3 5 4 6]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
ar=np.array([2,3.4,5.4,3,'a',7])

In [ ]:
ar

array(['2', '3.4', '5.4', '3', 'a', '7'], dtype='<U32')

In [ ]:
arr1

array([1, 3, 5, 4, 6])

In [ ]:
len(arr1)

5

In [ ]:
arr1[0]

1

In [ ]:
arr1[3]

4

In [ ]:
arr1[0:3]

array([1, 3, 5])

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.size

5

In [ ]:
arr1.ndim

1

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
#int8    range of values : -2^7 to (2^7)-1 = -128 to 127
#unsigned int8 range of values: 0 to (2^8)-1 = 0 to 255

#int64 : -2^63 to (2^63)-1

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.size

6

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr2.ndim

2

In [ ]:
arr3=np.array([[1,2,3],[4,5,6,7]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
arr3

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [ ]:
arr3.shape

(2,)

In [ ]:
arr3.ndim

1

In [ ]:
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr4.ndim

3

In [ ]:
arr4.size

8

In [ ]:
arr4.shape

(2, 2, 2)

In [ ]:
#reshaping of a numpy array

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.size

6

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr2=arr2.reshape(3,2)

In [ ]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2.shape

(3, 2)

In [ ]:
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
arr2.reshape(6,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
arr2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [ ]:
arr2.reshape(3,2,3)  #Error
#When individual values in the shape attribute are multiplied, we need to get the product as size of the numpy array

ValueError: ignored

In [ ]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr4.size

8

In [ ]:
arr4.shape

(2, 2, 2)

In [ ]:
arr4.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.size(arr4)

8

In [ ]:
#random method of numpy

In [ ]:
np.random.rand(4)

array([0.34034719, 0.66191216, 0.9055478 , 0.72003052])

In [ ]:
np.random.seed(14)
np.random.rand(4)

array([0.51394334, 0.77316505, 0.87042769, 0.00804695])

In [ ]:
np.random.randint(20,30,8)

array([21, 29, 21, 25, 28, 29, 25, 23])

In [ ]:
np.random.seed(13)
np.random.randint(20,30,8)

array([22, 20, 20, 26, 22, 24, 29, 23])

In [ ]:
np.random.seed(13)
np.random.randint(20,30,(2,4))

array([[22, 20, 20, 26],
       [22, 24, 29, 23]])

In [ ]:
#OTP generation
print(np.random.randint(0,10,6))

[3 2 1 8 5 5]


In [ ]:
#create an 1D array of 35 random integers between 100 and 150
#reshape it to a 2D array

In [ ]:
abc=np.random.randint(100,150,35)
abc

array([125, 149, 101, 116, 126, 107, 126, 147, 136, 135, 122, 133, 103,
       149, 135, 120, 148, 136, 143, 104, 127, 106, 145, 119, 143, 103,
       125, 116, 136, 129, 125, 109, 148, 102, 118])

In [ ]:
abc.shape

(35,)

In [ ]:
abc.ndim

1

In [ ]:
a1=abc.reshape(7,5)
a1

array([[125, 149, 101, 116, 126],
       [107, 126, 147, 136, 135],
       [122, 133, 103, 149, 135],
       [120, 148, 136, 143, 104],
       [127, 106, 145, 119, 143],
       [103, 125, 116, 136, 129],
       [125, 109, 148, 102, 118]])

In [ ]:
a1.shape

(7, 5)

In [ ]:
a1.ndim

2

In [ ]:
abc1=np.random.randint(100,150,(5,7))
abc1

array([[136, 123, 106, 124, 124, 112, 101],
       [138, 139, 123, 146, 124, 117, 137],
       [125, 113, 108, 109, 120, 116, 105],
       [115, 147, 100, 118, 135, 124, 149],
       [129, 119, 119, 114, 139, 132, 101]])

In [ ]:
np.random.seed(0)
a2=np.random.randint(10,20,9)
a2

array([15, 10, 13, 13, 17, 19, 13, 15, 12])

In [ ]:
np.unique(a2)

array([10, 12, 13, 15, 17, 19])

In [ ]:
np.unique(a2,return_counts=True)

(array([10, 12, 13, 15, 17, 19]), array([1, 1, 3, 2, 1, 1]))

In [ ]:
a2

array([15, 10, 13, 13, 17, 19, 13, 15, 12])

In [ ]:
np.sort(a2)

array([10, 12, 13, 13, 13, 15, 15, 17, 19])

In [ ]:
np.flip(a2)

array([12, 15, 13, 19, 17, 13, 13, 10, 15])

In [ ]:
a2

array([15, 10, 13, 13, 17, 19, 13, 15, 12])

In [ ]:
a3=np.append(a2,8)
a3

array([15, 10, 13, 13, 17, 19, 13, 15, 12,  8])

In [ ]:
a4=np.power(a3,2)
a4

array([225, 100, 169, 169, 289, 361, 169, 225, 144,  64])

In [ ]:
a4.dtype

dtype('int64')

In [ ]:
a5=np.sqrt(a4)
a5

array([15., 10., 13., 13., 17., 19., 13., 15., 12.,  8.])

In [ ]:
a5.dtype

dtype('float64')

In [ ]:
a3

array([15, 10, 13, 13, 17, 19, 13, 15, 12,  8])

In [ ]:
print(np.max(a3))
print(np.min(a3))
print(np.sum(a3))
print(np.mean(a3))
print(np.median(a3))

19
8
135
13.5
13.0


In [ ]:
x=np.array([2,3])
y=np.array([4,5])
np.add(x,y)

array([6, 8])

In [ ]:
x+y

array([6, 8])

In [ ]:
np.subtract(x,y)

array([-2, -2])

In [ ]:
#Conditions in numpy array

c=np.array([23,46,78,12,59,48,16])
c

array([23, 46, 78, 12, 59, 48, 16])

In [ ]:
c[c>30]

array([46, 78, 59, 48])

In [ ]:
c[c%2==0]

array([46, 78, 12, 48, 16])

In [ ]:
c[c%2!=0]

array([23, 59])

In [ ]:
c

array([23, 46, 78, 12, 59, 48, 16])

In [ ]:
np.where(c>30)

(array([1, 2, 4, 5]),)

In [ ]:
np.where(c%2==0)

(array([1, 2, 3, 5, 6]),)

In [ ]:
#How to take user input in a numpy array
a= np.array([],dtype='int8')
n=int(input("Enter the total number of elements: "))
for i in range(n):
  a=np.append(a,int(input("Enter the elements: ")))
a

Enter the total number of elements: 4
Enter the elements: 2
Enter the elements: 5
Enter the elements: 7
Enter the elements: 9


array([2, 5, 7, 9])

In [ ]:
abc1

array([[136, 123, 106, 124, 124, 112, 101],
       [138, 139, 123, 146, 124, 117, 137],
       [125, 113, 108, 109, 120, 116, 105],
       [115, 147, 100, 118, 135, 124, 149],
       [129, 119, 119, 114, 139, 132, 101]])

In [ ]:
np.save('myarray.csv',abc1)

In [ ]:
np.load("/content/myarray.csv.npy")

array([[136, 123, 106, 124, 124, 112, 101],
       [138, 139, 123, 146, 124, 117, 137],
       [125, 113, 108, 109, 120, 116, 105],
       [115, 147, 100, 118, 135, 124, 149],
       [129, 119, 119, 114, 139, 132, 101]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,dtype='uint8')

array([0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
np.zeros((5,5),dtype='uint8')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [ ]:
np.zeros([7,3],dtype='uint8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [ ]:
np.ones([7,3],dtype='uint8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [ ]:
np.ones([7,3],dtype='uint8')*255

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]], dtype=uint8)

In [ ]:
np.ones([7,3],dtype='uint8')*127

array([[127, 127, 127],
       [127, 127, 127],
       [127, 127, 127],
       [127, 127, 127],
       [127, 127, 127],
       [127, 127, 127],
       [127, 127, 127]], dtype=uint8)

In [ ]:
np.ones([2,2,2],dtype='uint8')*255

array([[[255, 255],
        [255, 255]],

       [[255, 255],
        [255, 255]]], dtype=uint8)

In [ ]:
np.ones(1)

array([1.])

In [ ]:
np.ones(1,dtype='uint8')

array([1], dtype=uint8)

In [ ]:
np.ones([1,1],dtype='uint8')

array([[1]], dtype=uint8)

In [ ]:
#Diagonal Elements
np.eye(1)

array([[1.]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(5,k=0,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(5,k=1,dtype='int')

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
np.eye(5,k=1,dtype='int')

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
b2=np.eye(5,k=-1,dtype='int')
b2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [ ]:
b2.shape

(5, 5)

In [ ]:
np.eye(4,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [ ]:
np.eye(4,5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(4,5,k=2,dtype=int)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [ ]:
np.eye(4,5,k=-2,dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
a3

array([15, 10, 13, 13, 17, 19, 13, 15, 12,  8])

In [ ]:
np.argmax(a3)

5

In [ ]:
np.max(a3)

19

In [ ]:
np.min(a3)

8

In [ ]:
np.argmin(a3)

9

In [ ]:
for i in range(10):
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.arange(100,9,-3)

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31,  28,  25,
        22,  19,  16,  13,  10])

In [ ]:
#create an 1D array from 1 to 12 and reshape it to (3,4) form

In [ ]:
start=int(input())
end=int(input())
np.arange(start,end).reshape(3,4)

1
13


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,5,2)

array([0., 5.])

In [ ]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [ ]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [ ]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [ ]:
#Matrix
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
type(mat1)

numpy.matrix

In [ ]:
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Euclidean distance

a=np.array([2,6])  #Point A (x1,y1)
b=np.array([5,8])  #Point B (x2,y2)

#sqrt(((5-2)^2)+((8-6)^2))
#sqrt(((3)^2)+((2)^2))
#sqrt((9+4))
#sqrt(13)
#3.6055

In [ ]:
np.sqrt(np.sum(np.square(np.subtract(a,b))))

3.605551275463989

In [ ]:
#Normalization
a=np.array([12,14,456,784,342,2])
b=np.array([1,7,4,9,2,5])

In [ ]:
a_max=np.max(a)
a_min=np.min(a)
a_norm=(a-a_min)/(a_max-a_min)
a_norm

array([0.01278772, 0.01534527, 0.58056266, 1.        , 0.43478261,
       0.        ])

In [ ]:
b_max=np.max(b)
b_min=np.min(b)
b_norm=(b-b_min)/(b_max-b_min)
b_norm

array([0.   , 0.75 , 0.375, 1.   , 0.125, 0.5  ])